---
#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

#MySQL Settings
mysql_root_password: "devops123"
mysql_db: "wordpress"
mysql_user: "ankit"
mysql_password: "redhat"

#HTTP Settings
http_host: "127.0.0.1"
http_conf: "127.0.0.1.conf"
http_port: "80"